#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "====================================="
echo "💅 Running Prettier (npm run format)..."
echo "====================================="

npm run format

echo "📦 Re-staging formatted files..."
git add .

echo "✅ Formatting complete."
